# -*- coding: utf-8 -*-
"""emmanuel_policyholder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7TIgBY7ym66rcYRA6RFbsKiE6hd4mlM

# **Policyholder Class**
"""

class My_Policyholder_Class:
    def __init__(self, name, policy_id):
        self.name = name
        self.policy_id = policy_id
        self.status = 'active'
        self.products = []

    def register(self): # Here, I am creating a function that can help witht the task of new registeration
        print(f"Policyholder {self.name} with ID {self.policy_id} has been registered.")

    def suspend(self): # Here, I am creating a function that can help with the task of suspension
        self.status = 'suspended'
        print(f"Policyholder {self.name} with ID {self.policy_id} has been suspended.")

    def reactivate(self): # Here, I am creating a function that can help with the task of reactivation
        self.status = 'active'
        print(f"Policyholder {self.name} with ID {self.policy_id} has been reactivated.")

    def add_product(self, product): # Here, I am creating a function that can help with the assignment of a new product
        self.products.append(product)
        print(f"Product {product.name} has been added to policyholder {self.name}'s account.")

    def display_details(self):
        print(f"Policyholder Name: {self.name}")
        print(f"Policyholder ID: {self.policy_id}")
        print(f"Status: {self.status}")
        print("Products: ", ", ".join([product.name for product in self.products]))

