# -*- coding: utf-8 -*-
"""emmanuel_product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7zyy8g_ieIU_VloE_X79dx7CwTETuRl

# **Product Class**
"""

class My_Product_Class:
    def __init__(self, product_id, name, description, price):
        self.product_id = product_id
        self.name = name
        self.description = description
        self.price = price
        self.status = 'active'

    def create_product(self): # Here, I am creating a function that can help with the task of creating a product
        print(f"Product {self.name} has been created.")

    def update_product(self, name=None, description=None, price=None): # Here, I am creating a function that can help with the task of updating a product
        if name:
            self.name = name
        if description:
            self.description = description
        if price:
            self.price = price
        print(f"Product {self.name} has been updated.")

    def suspend_product(self): # Here, I am creating a function that can help with the task of suspending a product
        self.status = 'suspended'
        print(f"Product {self.name} has been suspended.")

