# -*- coding: utf-8 -*-
"""emmanuel_payment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ap6Wop5PCRuqRm1rwI5JDW0tB_asAzn1

# **Payment Class**
"""

class My_Payment_Class:
    def __init__(self, payment_id, policyholder_id, amount, date):
        self.payment_id = payment_id
        self.policyholder_id = policyholder_id
        self.amount = amount
        self.date = date
        self.status = 'paid'

    def process_payment(self): # Here, I am creating a function that can help with the task of payment processing
        print(f"Payment of {self.amount} for Policyholder ID {self.policyholder_id} has been processed.")

    def send_reminder(self): # Here, I am creating a function that can help with the task of sending reminders
        print(f"Reminder: Payment for Policyholder ID {self.policyholder_id} is due.")

    def apply_penalty(self, penalty_amount): # Here, I am creating a function that can help with the task of applying penalties
        self.amount += penalty_amount
        print(f"A penalty of {penalty_amount} has been applied. New amount due: {self.amount}.")

